### ISSUE TITLE
Handling JSON records

### ISSUE THREAD

**Issue by yinleon** [SMAPPNYU/smappdragon#31]
the json_collection doesn't seem to be able to handle json records I.E.
```
[
  {"a": 1},
  {"a": 2} 
]
```
Looks like collections are like this:
```
  {"a": 1},
  {"a": 2} 
```

**Comment by yvan** [comment]
this is because the json collection streams each object from memories, whereas a json list (what you have posted) to be loaded as json, needs to be loaded into memory all at once.

**Comment by yvan** [comment]
considering this closed as we probably shouldn't add support for json lists.
