### ISSUE TITLE
Add Language Counter

### ISSUE THREAD

**Issue by jonathannagler** [SMAPPNYU/smappdragon#7]
We could use a function to count:

a) The number of tweets Twitter THINKS are in (english, spanish) in a corpus
b) The number of tweets that we run through some filter and decide are predominantly  in (english, spanish) from a corpus).

We could use a function that would take an individual tweet and return:

a) Tweet is predominantly english-language text
b) Tweet is predominantly spanish-language text
c) Tweet has at least K spanish-language words in it
d) Tweets has at least K english-language words in it.

**Comment by yvan** [comment]
these are two separate things.

a )would go on smappdragon.

b)  would go on smappboa.

a-d) smappboa

**Comment by yvan** [comment]
file them here:

https://github.com/SMAPPNYU/smappboa/issues

**Comment by yvan** [comment]
actually all of this will probably go in smappboa.

**Comment by Nickhil-Sethi** [comment]
Hey Yvan,

Apparently I’m still on this email list. Please remove me.

-N

**Comment by dpenfoldbrown** [comment]
Hey Mano,

You're "following" the repo, so it will drop you the emails. Can just got
to its page and click 'unfollow' somewhere..
